# Generated by Django 5.1.1 on 2024-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
